### ISSUE TITLE
Black flickering on image swiping

### ISSUE THREAD

**Issue by dantp-ai** [spiritinlife/EasySlideShow4Android#2]
I nested all the code as mentioned in the docs,  in onCreateView() of a fragment. On image swiping, I get a black flickering. What could be the problem?

**Comment by spiritinlife** [comment]
Hmm it seems i have put a funky animation , like old tv bad signal style when changing images. If you set Waiting to false everywhere in code it will dissapear. Anyway since i see there is some interest in this library idea i am planning to make it more solid in the upcoming weeks so bare with me for some changes :)
